apiVersion: v1
kind: Service
metadata:
    name: "azuremltb-6425"
    labels:
        app: "azuremltb-6425"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "azuremltb-6425"